/* AppAS Application for assignment 3 */
package Ex3;
//libraries
import Ex1.*;
import javax.swing.JFrame;
import java.io.File;
import Ex4.readSQL;
import java.awt.Dimension;
import java.awt.Point;
import java.awt.Toolkit;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.HashMap;
import java.util.Map;
import javax.swing.JOptionPane;
import javax.swing.UIManager;

/**
 * Main window of the AppAS.
 * @author Alexey Titov   and   Shalom Weinberger
 * @version 2
 */
public class AppAS extends JFrame {

    //define variables
    private static final long serialVersionUID = 8L;
    private static final HelpFunctionEx3 hf=new HelpFunctionEx3();
    private int flag=0;
    private boolean flag_UNDO=false;
    private Filter first;
    private Filter second;
    private Filter union;
    private static Map<String,String> TableFiles=new HashMap<>();
    private static Map<String,String> TableFolder=new HashMap<>();
    private static Map<String,String> TableSQL=new HashMap<>();
    /**
     * main for application
     * @param args it does not matter
     */
    public static void main(String[] args)
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            javax.swing.UIManager.LookAndFeelInfo[] installedLookAndFeels=javax.swing.UIManager.getInstalledLookAndFeels();
            for (UIManager.LookAndFeelInfo installedLookAndFeel : installedLookAndFeels) {
                if ("Nimbus".equals(installedLookAndFeel.getName())) {
                    javax.swing.UIManager.setLookAndFeel(installedLookAndFeel.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AppAS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        /* Create and display the form */
        Thread t1 = new Thread(new RunnableImpl());     //SwingUtilities.invokeLater(new RunnableImpl());
        Thread t2 = new ThreadTable();
        Thread t3 = new ThreadTableFolder();
        Thread t4 = new ThreadTableSQL();
        t1.start();
        t2.start();
        t3.start();
        t4.start();
    }
    /** Creates new form AppAS */
    public AppAS() 
    {
		File file = new File(AppAS.class.getProtectionDomain().getCodeSource().getLocation().getPath());
        initComponents();
        HelpFunctionEx3.initDatabase(file.getPath()+"s\\");
        //setIcon();
        pack();
        // Center in the screen
        Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();
        Dimension frameSize = getSize();
        setLocation(new Point((screenSize.width - frameSize.width) / 2,
                              (screenSize.height - frameSize.width) / 2));
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroupLogical = new javax.swing.ButtonGroup();
        buttonGroupTypeFilter = new javax.swing.ButtonGroup();
        jTabbedPanelTask = new javax.swing.JTabbedPane();
        jPanelALGO = new javax.swing.JPanel();
        jLabelSalgorithm = new javax.swing.JLabel();
        jLabelRow = new javax.swing.JLabel();
        jTextFieldRowTS = new javax.swing.JTextField();
        jButtonOKGPSTS = new javax.swing.JButton();
        jLabelMAC1 = new javax.swing.JLabel();
        jLabelMAC2 = new javax.swing.JLabel();
        jLabelMAC3 = new javax.swing.JLabel();
        jFormattedTextFieldMAC1 = new javax.swing.JFormattedTextField();
        jFormattedTextFieldMAC2 = new javax.swing.JFormattedTextField();
        jFormattedTextFieldMAC3 = new javax.swing.JFormattedTextField();
        jLabelSignal1 = new javax.swing.JLabel();
        jLabelSignal2 = new javax.swing.JLabel();
        jLabelSignal3 = new javax.swing.JLabel();
        jFormattedTextFieldSignal1 = new javax.swing.JFormattedTextField();
        jFormattedTextFieldSignal2 = new javax.swing.JFormattedTextField();
        jFormattedTextFieldSignal3 = new javax.swing.JFormattedTextField();
        jButtonOKThreeMAC = new javax.swing.JButton();
        jButtonFirstALGO = new javax.swing.JButton();
        jLabelFirstAlgorithm = new javax.swing.JLabel();
        jFormattedTextFieldMACfa = new javax.swing.JFormattedTextField();
        jLabelMACfa = new javax.swing.JLabel();
        jLabelLantitude = new javax.swing.JLabel();
        jLabelLongtitude = new javax.swing.JLabel();
        jLabelAltitude = new javax.swing.JLabel();
        jTextFieldLantitude = new javax.swing.JTextField();
        jTextFieldLongtitude = new javax.swing.JTextField();
        jTextFieldAltitude = new javax.swing.JTextField();
        jPanelIOput = new javax.swing.JPanel();
        jLabelAddFolder = new javax.swing.JLabel();
        jLabelAddFile = new javax.swing.JLabel();
        jLabelCB = new javax.swing.JLabel();
        jLabelSD = new javax.swing.JLabel();
        jLabelSK = new javax.swing.JLabel();
        jLabelShowData = new javax.swing.JLabel();
        jTextFieldNameFolder = new javax.swing.JTextField();
        jTextFieldNameFile = new javax.swing.JTextField();
        jTextFieldShowData = new javax.swing.JTextField();
        jTextFieldNameSaveFile = new javax.swing.JTextField();
        jTextFieldSaveKml = new javax.swing.JTextField();
        jButtonClearOK = new javax.swing.JButton();
        jButtonBrowseFolder = new javax.swing.JButton();
        jButtonOKFolder = new javax.swing.JButton();
        jButtonBrowseFile = new javax.swing.JButton();
        jButtonOKFile = new javax.swing.JButton();
        jButtonSaveFile = new javax.swing.JButton();
        jButtonSaveKML = new javax.swing.JButton();
        jButtonShowData = new javax.swing.JButton();
        jTextFieldFilter = new javax.swing.JTextField();
        jPanelFilters = new javax.swing.JPanel();
        jLabelTime = new javax.swing.JLabel();
        jFormattedTextFieldFROM = new javax.swing.JFormattedTextField();
        jFormattedTextFieldTO = new javax.swing.JFormattedTextField();
        jLabelFROMTime = new javax.swing.JLabel();
        jLabelTOTime = new javax.swing.JLabel();
        jRadioButtonAnd = new javax.swing.JRadioButton();
        jRadioButtonOr = new javax.swing.JRadioButton();
        jRadioButtonNOTtime = new javax.swing.JRadioButton();
        jLabelAND = new javax.swing.JLabel();
        jLabelOR = new javax.swing.JLabel();
        jLabelNOT = new javax.swing.JLabel();
        jLabelLocation = new javax.swing.JLabel();
        jLabelX = new javax.swing.JLabel();
        jFormattedTextFieldLantitude = new javax.swing.JFormattedTextField();
        jLabelY = new javax.swing.JLabel();
        jFormattedTextFieldLongtitude = new javax.swing.JFormattedTextField();
        jRadioButtonTime = new javax.swing.JRadioButton();
        jRadioButtonLocation = new javax.swing.JRadioButton();
        jLabelRadius = new javax.swing.JLabel();
        jFormattedTextFieldRadius = new javax.swing.JFormattedTextField();
        jLabelDevice = new javax.swing.JLabel();
        jTextFieldDeviceName = new javax.swing.JTextField();
        jRadioButtonDecvice = new javax.swing.JRadioButton();
        jButtonFilter = new javax.swing.JButton();
        jButtonCancel = new javax.swing.JButton();
        jButtonUPdate = new javax.swing.JButton();
        jRadioButtonNOTlocation = new javax.swing.JRadioButton();
        jRadioButtonNOTdevice = new javax.swing.JRadioButton();
        jLabelNumberFilters = new javax.swing.JLabel();
        jButtonUNDO = new javax.swing.JButton();
        jPanelSQL = new javax.swing.JPanel();
        jLabelIP = new javax.swing.JLabel();
        jFormattedTextFieldIP = new javax.swing.JFormattedTextField();
        jLabelPORT = new javax.swing.JLabel();
        jFormattedTextFieldPORT = new javax.swing.JFormattedTextField();
        jLabelUSER = new javax.swing.JLabel();
        jTextFieldUSER = new javax.swing.JTextField();
        jLabelPASSWORD = new javax.swing.JLabel();
        jTextFieldPASSWORD = new javax.swing.JTextField();
        jLabelDB = new javax.swing.JLabel();
        jTextFieldDB = new javax.swing.JTextField();
        jLabelTABLE = new javax.swing.JLabel();
        jTextFieldTable = new javax.swing.JTextField();
        jButtonConnect = new javax.swing.JButton();
        mainMenu = new javax.swing.JMenuBar();
        fileMenu = new javax.swing.JMenu();
        aboutMenuItem = new javax.swing.JMenuItem();
        exitMenuItem = new javax.swing.JMenuItem();

        setTitle("AppWIFI");
        setMaximumSize(new java.awt.Dimension(660, 500));
        setMinimumSize(new java.awt.Dimension(660, 500));
        setPreferredSize(new java.awt.Dimension(660, 500));
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                exitForm(evt);
            }
        });

        jTabbedPanelTask.setMaximumSize(new java.awt.Dimension(660, 480));
        jTabbedPanelTask.setMinimumSize(new java.awt.Dimension(660, 480));
        jTabbedPanelTask.setPreferredSize(new java.awt.Dimension(660, 480));

        jPanelALGO.setBackground(new java.awt.Color(255, 204, 204));
        jPanelALGO.setMinimumSize(new java.awt.Dimension(660, 450));
        jPanelALGO.setPreferredSize(new java.awt.Dimension(660, 450));
        jPanelALGO.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                jPanelALGOAncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
        });

        jLabelSalgorithm.setText("Second algorithm ");

        jLabelRow.setText("ROW");

        jTextFieldRowTS.setText("row as comb_no_gps_ts1.csv");

        jButtonOKGPSTS.setText("OK");
        jButtonOKGPSTS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonOKGPSTSActionPerformed(evt);
            }
        });

        jLabelMAC1.setText("MAC");

        jLabelMAC2.setText("MAC");

        jLabelMAC3.setText("MAC");

        jFormattedTextFieldMAC1.setColumns(20);
        try {
            jFormattedTextFieldMAC1.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("HH:HH:HH:HH:HH:HH")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jFormattedTextFieldMAC1.setText("");
        jFormattedTextFieldMAC1.setMinimumSize(new java.awt.Dimension(150, 30));
        jFormattedTextFieldMAC1.setPreferredSize(new java.awt.Dimension(150, 30));

        jFormattedTextFieldMAC2.setColumns(20);
        try {
            jFormattedTextFieldMAC2.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("HH:HH:HH:HH:HH:HH")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jFormattedTextFieldMAC2.setText("");
        jFormattedTextFieldMAC2.setMinimumSize(new java.awt.Dimension(150, 30));
        jFormattedTextFieldMAC2.setPreferredSize(new java.awt.Dimension(150, 30));

        jFormattedTextFieldMAC3.setColumns(20);
        try {
            jFormattedTextFieldMAC3.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("HH:HH:HH:HH:HH:HH")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jFormattedTextFieldMAC3.setText("");
        jFormattedTextFieldMAC3.setMinimumSize(new java.awt.Dimension(150, 30));
        jFormattedTextFieldMAC3.setPreferredSize(new java.awt.Dimension(150, 30));

        jLabelSignal1.setText("Signal");

        jLabelSignal2.setText("Signal");

        jLabelSignal3.setText("Signal");

        jFormattedTextFieldSignal1.setColumns(4);
        jFormattedTextFieldSignal1.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("###"))));

        jFormattedTextFieldSignal2.setColumns(4);
        jFormattedTextFieldSignal2.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("###"))));

        jFormattedTextFieldSignal3.setColumns(4);
        jFormattedTextFieldSignal3.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("###"))));

        jButtonOKThreeMAC.setText("OK");
        jButtonOKThreeMAC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonOKThreeMACActionPerformed(evt);
            }
        });

        jButtonFirstALGO.setText("First algorithm");
        jButtonFirstALGO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonFirstALGOActionPerformed(evt);
            }
        });

        jLabelFirstAlgorithm.setText("First algorithm");

        jFormattedTextFieldMACfa.setColumns(20);
        try {
            jFormattedTextFieldMACfa.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("HH:HH:HH:HH:HH:HH")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jFormattedTextFieldMACfa.setText("11:22:33:44:55:66  ");

        jLabelMACfa.setText("MAC");

        jLabelLantitude.setText("Lantitude");

        jLabelLongtitude.setText("Longtitude");

        jLabelAltitude.setText("Altitude");

        jTextFieldLantitude.setEditable(false);

        jTextFieldLongtitude.setEditable(false);

        jTextFieldAltitude.setEditable(false);

        javax.swing.GroupLayout jPanelALGOLayout = new javax.swing.GroupLayout(jPanelALGO);
        jPanelALGO.setLayout(jPanelALGOLayout);
        jPanelALGOLayout.setHorizontalGroup(
            jPanelALGOLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelALGOLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelALGOLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButtonFirstALGO)
                    .addGroup(jPanelALGOLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanelALGOLayout.createSequentialGroup()
                            .addComponent(jLabelMAC2)
                            .addGap(18, 18, 18)
                            .addComponent(jFormattedTextFieldMAC2, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE))
                        .addComponent(jLabelSalgorithm, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabelRow, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jButtonOKGPSTS, javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanelALGOLayout.createSequentialGroup()
                            .addComponent(jLabelMAC1)
                            .addGap(18, 18, 18)
                            .addComponent(jFormattedTextFieldMAC1, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanelALGOLayout.createSequentialGroup()
                            .addComponent(jLabelMAC3)
                            .addGap(18, 18, 18)
                            .addComponent(jFormattedTextFieldMAC3, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanelALGOLayout.createSequentialGroup()
                            .addComponent(jLabelMACfa, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jFormattedTextFieldMACfa, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGroup(jPanelALGOLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelALGOLayout.createSequentialGroup()
                        .addGap(57, 57, 57)
                        .addComponent(jLabelLantitude)
                        .addGap(58, 58, 58))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelALGOLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldLantitude, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                .addGroup(jPanelALGOLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabelLongtitude)
                    .addComponent(jTextFieldLongtitude, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanelALGOLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelALGOLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabelAltitude)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanelALGOLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jTextFieldAltitude, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelALGOLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonOKThreeMAC)
                .addGap(93, 93, 93))
            .addGroup(jPanelALGOLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jTextFieldRowTS)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanelALGOLayout.createSequentialGroup()
                .addGroup(jPanelALGOLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelALGOLayout.createSequentialGroup()
                        .addGap(334, 334, 334)
                        .addGroup(jPanelALGOLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelALGOLayout.createSequentialGroup()
                                .addComponent(jLabelSignal1)
                                .addGap(18, 18, 18)
                                .addComponent(jFormattedTextFieldSignal1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanelALGOLayout.createSequentialGroup()
                                .addComponent(jLabelSignal3)
                                .addGap(18, 18, 18)
                                .addComponent(jFormattedTextFieldSignal3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanelALGOLayout.createSequentialGroup()
                                .addComponent(jLabelSignal2)
                                .addGap(18, 18, 18)
                                .addComponent(jFormattedTextFieldSignal2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanelALGOLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabelFirstAlgorithm)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelALGOLayout.setVerticalGroup(
            jPanelALGOLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelALGOLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelSalgorithm)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabelRow)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldRowTS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonOKGPSTS)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelALGOLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelMAC1)
                    .addComponent(jFormattedTextFieldMAC1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelSignal1)
                    .addComponent(jFormattedTextFieldSignal1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelALGOLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelMAC2)
                    .addComponent(jFormattedTextFieldMAC2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelSignal2)
                    .addComponent(jFormattedTextFieldSignal2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelALGOLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelMAC3)
                    .addComponent(jFormattedTextFieldMAC3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelSignal3)
                    .addComponent(jFormattedTextFieldSignal3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonOKThreeMAC))
                .addGap(18, 18, 18)
                .addComponent(jLabelFirstAlgorithm)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelALGOLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jFormattedTextFieldMACfa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelMACfa)
                    .addComponent(jLabelLongtitude)
                    .addComponent(jLabelLantitude)
                    .addComponent(jLabelAltitude))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelALGOLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldAltitude, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldLantitude, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldLongtitude, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(4, 4, 4)
                .addComponent(jButtonFirstALGO)
                .addGap(0, 98, Short.MAX_VALUE))
        );

        jTabbedPanelTask.addTab("Algo", jPanelALGO);
        jPanelALGO.getAccessibleContext().setAccessibleName("ALGO");

        jPanelIOput.setBackground(new java.awt.Color(204, 255, 255));
        jPanelIOput.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        jPanelIOput.setMinimumSize(new java.awt.Dimension(660, 450));
        jPanelIOput.setPreferredSize(new java.awt.Dimension(660, 450));
        jPanelIOput.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                jPanelIOputAncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
        });

        jLabelAddFolder.setText("Add Folder of Wigle files");

        jLabelAddFile.setText("Add wigle file");

        jLabelCB.setText("Clear database");

        jLabelSD.setText("Save the data in a special file");
        jLabelSD.setMinimumSize(new java.awt.Dimension(160, 14));
        jLabelSD.setPreferredSize(new java.awt.Dimension(160, 14));

        jLabelSK.setText("Save the database in kml format");
        jLabelSK.setMaximumSize(new java.awt.Dimension(180, 14));
        jLabelSK.setMinimumSize(new java.awt.Dimension(180, 14));
        jLabelSK.setPreferredSize(new java.awt.Dimension(180, 14));

        jLabelShowData.setText("Show data");

        jTextFieldNameFolder.setEditable(false);
        jTextFieldNameFolder.setColumns(25);
        jTextFieldNameFolder.setText("Name Folder");
        jTextFieldNameFolder.setMinimumSize(new java.awt.Dimension(55, 20));

        jTextFieldNameFile.setEditable(false);
        jTextFieldNameFile.setColumns(25);
        jTextFieldNameFile.setText("Name File ");
        jTextFieldNameFile.setMinimumSize(new java.awt.Dimension(55, 20));

        jTextFieldShowData.setEditable(false);
        jTextFieldShowData.setColumns(25);
        jTextFieldShowData.setText("Data:");
        jTextFieldShowData.setMinimumSize(new java.awt.Dimension(55, 20));

        jTextFieldNameSaveFile.setEditable(false);
        jTextFieldNameSaveFile.setColumns(25);
        jTextFieldNameSaveFile.setText("Save File");
        jTextFieldNameSaveFile.setMinimumSize(new java.awt.Dimension(55, 20));

        jTextFieldSaveKml.setEditable(false);
        jTextFieldSaveKml.setColumns(25);
        jTextFieldSaveKml.setText("KML File");
        jTextFieldSaveKml.setMinimumSize(new java.awt.Dimension(55, 20));

        jButtonClearOK.setText("Clear");
        jButtonClearOK.setToolTipText("");
        jButtonClearOK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonClearOKActionPerformed(evt);
            }
        });

        jButtonBrowseFolder.setText("Browse");
        jButtonBrowseFolder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBrowseFolderActionPerformed(evt);
            }
        });

        jButtonOKFolder.setText("OK");
        jButtonOKFolder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonOKFolderActionPerformed(evt);
            }
        });

        jButtonBrowseFile.setText("Browse");
        jButtonBrowseFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBrowseFileActionPerformed(evt);
            }
        });

        jButtonOKFile.setText("OK");
        jButtonOKFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonOKFileActionPerformed(evt);
            }
        });

        jButtonSaveFile.setText("Save");
        jButtonSaveFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSaveFileActionPerformed(evt);
            }
        });

        jButtonSaveKML.setText("Save");
        jButtonSaveKML.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSaveKMLActionPerformed(evt);
            }
        });

        jButtonShowData.setText("Show");
        jButtonShowData.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
               jButtonShowDataActionPerformed(evt);
            }
        });

        jTextFieldFilter.setEditable(false);
        jTextFieldFilter.setColumns(50);
        jTextFieldFilter.setText("Filter:");

        javax.swing.GroupLayout jPanelIOputLayout = new javax.swing.GroupLayout(jPanelIOput);
        jPanelIOput.setLayout(jPanelIOputLayout);
        jPanelIOputLayout.setHorizontalGroup(
            jPanelIOputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelIOputLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelIOputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelIOputLayout.createSequentialGroup()
                        .addGroup(jPanelIOputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelAddFile, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelSK, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelAddFolder, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelShowData, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelCB, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelSD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(7, 7, 7)
                        .addGroup(jPanelIOputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jTextFieldSaveKml, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jTextFieldNameSaveFile, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jTextFieldNameFile, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jTextFieldNameFolder, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jTextFieldShowData, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 22, Short.MAX_VALUE)
                        .addGroup(jPanelIOputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(jButtonSaveKML, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButtonSaveFile, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButtonBrowseFile, javax.swing.GroupLayout.DEFAULT_SIZE, 89, Short.MAX_VALUE)
                            .addComponent(jButtonBrowseFolder, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE))
                    .addGroup(jPanelIOputLayout.createSequentialGroup()
                        .addGroup(jPanelIOputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButtonShowData)
                            .addComponent(jTextFieldFilter, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(jPanelIOputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jButtonOKFolder, javax.swing.GroupLayout.DEFAULT_SIZE, 69, Short.MAX_VALUE)
                    .addComponent(jButtonOKFile, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(36, 36, 36))
            .addGroup(jPanelIOputLayout.createSequentialGroup()
                .addGap(197, 197, 197)
                .addComponent(jButtonClearOK)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanelIOputLayout.setVerticalGroup(
            jPanelIOputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelIOputLayout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addGroup(jPanelIOputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelAddFolder)
                    .addComponent(jTextFieldNameFolder, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonBrowseFolder)
                    .addComponent(jButtonOKFolder))
                .addGap(29, 29, 29)
                .addGroup(jPanelIOputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelAddFile)
                    .addComponent(jTextFieldNameFile, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonBrowseFile)
                    .addComponent(jButtonOKFile))
                .addGap(28, 28, 28)
                .addGroup(jPanelIOputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanelIOputLayout.createSequentialGroup()
                        .addGroup(jPanelIOputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelCB)
                            .addComponent(jButtonClearOK))
                        .addGap(30, 30, 30)
                        .addComponent(jLabelSD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelIOputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTextFieldNameSaveFile, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButtonSaveFile)))
                .addGap(27, 27, 27)
                .addGroup(jPanelIOputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelIOputLayout.createSequentialGroup()
                        .addGroup(jPanelIOputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelSK, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldSaveKml, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonSaveKML))
                        .addGap(28, 28, 28)
                        .addComponent(jLabelShowData))
                    .addComponent(jTextFieldShowData, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jTextFieldFilter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(jButtonShowData)
                .addContainerGap(95, Short.MAX_VALUE))
        );

        jButtonBrowseFolder.getAccessibleContext().setAccessibleName("jButtonBrowseFolder");

        jTabbedPanelTask.addTab("IOput", null, jPanelIOput, "");
        jPanelIOput.getAccessibleContext().setAccessibleName("IOput");

        jPanelFilters.setBackground(new java.awt.Color(255, 255, 204));
        jPanelFilters.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        jPanelFilters.setMinimumSize(new java.awt.Dimension(660, 450));
        jPanelFilters.setPreferredSize(new java.awt.Dimension(660, 450));
        jPanelFilters.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                jPanelFiltersAncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
        });

        jLabelTime.setText("Time");

        Date date = new Date();
        SimpleDateFormat formatter = new SimpleDateFormat("yyyy-MM-dd HH:mm:ss");
        String dateString = formatter.format(date);
        jFormattedTextFieldFROM.setColumns(20);
        try {
            jFormattedTextFieldFROM.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("####-##-## ##:##:##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jFormattedTextFieldFROM.setText(dateString);

        jFormattedTextFieldTO.setColumns(20);
        try {
            jFormattedTextFieldTO.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("####-##-## ##:##:##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jFormattedTextFieldTO.setText(dateString);

        jLabelFROMTime.setText("FROM");

        jLabelTOTime.setText("TO");

        buttonGroupLogical.add(jRadioButtonAnd);

        buttonGroupLogical.add(jRadioButtonOr);
        jRadioButtonOr.setSelected(true);

        buttonGroupTypeFilter.add(jRadioButtonNOTtime);

        jLabelAND.setText("AND");

        jLabelOR.setText("OR");

        jLabelNOT.setText("NOT");

        jLabelLocation.setText("Location");

        jLabelX.setText("lantitude");

        jFormattedTextFieldLantitude.setColumns(18);
        jFormattedTextFieldLantitude.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#.00000000"))));
        jFormattedTextFieldLantitude.setText("32.33");

        jLabelY.setText("longitude");

        jFormattedTextFieldLongtitude.setColumns(18);
        jFormattedTextFieldLongtitude.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#.00000000"))));
        jFormattedTextFieldLongtitude.setText("35.33");

        buttonGroupTypeFilter.add(jRadioButtonTime);

        buttonGroupTypeFilter.add(jRadioButtonLocation);

        jLabelRadius.setText("Radius");

        jFormattedTextFieldRadius.setColumns(8);
        jFormattedTextFieldRadius.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("0.00000000"))));
        jFormattedTextFieldRadius.setText("0.003");
        jFormattedTextFieldRadius.setMinimumSize(new java.awt.Dimension(8, 20));

        jLabelDevice.setText("Device");

        jTextFieldDeviceName.setText("device name");

        buttonGroupTypeFilter.add(jRadioButtonDecvice);
        jRadioButtonDecvice.setSelected(true);

        jButtonFilter.setText("Filter");
        jButtonFilter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonFilterActionPerformed(evt);
            }
        });

        jButtonCancel.setText("Cancel");
        jButtonCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelActionPerformed(evt);
            }
        });

        jButtonUPdate.setText("UPdate");
        jButtonUPdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonUPdateActionPerformed(evt);
            }
        });

        buttonGroupTypeFilter.add(jRadioButtonNOTlocation);

        buttonGroupTypeFilter.add(jRadioButtonNOTdevice);

        jLabelNumberFilters.setText("0");

        jButtonUNDO.setText("UNDO");
        jButtonUNDO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonUNDOActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelFiltersLayout = new javax.swing.GroupLayout(jPanelFilters);
        jPanelFilters.setLayout(jPanelFiltersLayout);
        jPanelFiltersLayout.setHorizontalGroup(
            jPanelFiltersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelFiltersLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelFiltersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelFiltersLayout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addComponent(jLabelNumberFilters)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanelFiltersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(jLabelAND)
                            .addComponent(jRadioButtonAnd))
                        .addGap(18, 18, 18)
                        .addGroup(jPanelFiltersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(jRadioButtonOr)
                            .addComponent(jLabelOR))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanelFiltersLayout.createSequentialGroup()
                        .addGroup(jPanelFiltersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelFiltersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(jPanelFiltersLayout.createSequentialGroup()
                                    .addGroup(jPanelFiltersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanelFiltersLayout.createSequentialGroup()
                                            .addGap(8, 8, 8)
                                            .addComponent(jLabelX))
                                        .addComponent(jLabelRadius, javax.swing.GroupLayout.Alignment.TRAILING))
                                    .addGap(18, 18, 18)
                                    .addGroup(jPanelFiltersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jFormattedTextFieldRadius, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(jPanelFiltersLayout.createSequentialGroup()
                                            .addGroup(jPanelFiltersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addGroup(jPanelFiltersLayout.createSequentialGroup()
                                                    .addComponent(jButtonCancel)
                                                    .addGap(110, 110, 110))
                                                .addGroup(jPanelFiltersLayout.createSequentialGroup()
                                                    .addComponent(jFormattedTextFieldLantitude, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addGap(18, 18, 18)
                                                    .addComponent(jLabelY)))
                                            .addGroup(jPanelFiltersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addGroup(jPanelFiltersLayout.createSequentialGroup()
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                    .addComponent(jFormattedTextFieldLongtitude, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelFiltersLayout.createSequentialGroup()
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                    .addComponent(jButtonUPdate))))))
                                .addGroup(jPanelFiltersLayout.createSequentialGroup()
                                    .addGap(10, 10, 10)
                                    .addComponent(jLabelFROMTime, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(jFormattedTextFieldFROM, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(jLabelTOTime)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(jFormattedTextFieldTO, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(jLabelLocation)
                                .addComponent(jLabelTime)
                                .addComponent(jLabelDevice)
                                .addComponent(jTextFieldDeviceName))
                            .addComponent(jButtonFilter))
                        .addGap(57, 57, 57)
                        .addGroup(jPanelFiltersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelFiltersLayout.createSequentialGroup()
                                .addGroup(jPanelFiltersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jRadioButtonLocation)
                                    .addComponent(jRadioButtonTime)
                                    .addComponent(jRadioButtonDecvice))
                                .addGap(18, 18, 18)
                                .addGroup(jPanelFiltersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabelNOT)
                                    .addGroup(jPanelFiltersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                                        .addComponent(jRadioButtonNOTdevice)
                                        .addComponent(jRadioButtonNOTlocation, javax.swing.GroupLayout.Alignment.LEADING))
                                    .addComponent(jRadioButtonNOTtime)))
                            .addComponent(jButtonUNDO))
                        .addContainerGap(132, Short.MAX_VALUE))))
        );

        jPanelFiltersLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jRadioButtonDecvice, jRadioButtonLocation, jRadioButtonNOTdevice, jRadioButtonNOTlocation, jRadioButtonNOTtime, jRadioButtonTime});

        jPanelFiltersLayout.setVerticalGroup(
            jPanelFiltersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelFiltersLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelFiltersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelFiltersLayout.createSequentialGroup()
                        .addComponent(jLabelTime)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanelFiltersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jFormattedTextFieldFROM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jFormattedTextFieldTO, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelFROMTime)
                            .addComponent(jLabelTOTime))
                        .addGap(11, 11, 11)
                        .addComponent(jLabelLocation)
                        .addGap(5, 5, 5)
                        .addGroup(jPanelFiltersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelX)
                            .addComponent(jFormattedTextFieldLantitude, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelY)
                            .addComponent(jFormattedTextFieldLongtitude, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanelFiltersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelRadius)
                            .addComponent(jFormattedTextFieldRadius, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabelDevice)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextFieldDeviceName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelFiltersLayout.createSequentialGroup()
                        .addComponent(jLabelNOT)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanelFiltersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jRadioButtonNOTtime)
                            .addComponent(jRadioButtonTime, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(33, 33, 33)
                        .addGroup(jPanelFiltersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jRadioButtonLocation, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jRadioButtonNOTlocation))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 66, Short.MAX_VALUE)
                        .addGroup(jPanelFiltersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jRadioButtonNOTdevice, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jRadioButtonDecvice, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 7, Short.MAX_VALUE)
                .addGroup(jPanelFiltersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelAND)
                    .addComponent(jLabelOR))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelFiltersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanelFiltersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jRadioButtonOr)
                        .addComponent(jRadioButtonAnd))
                    .addComponent(jLabelNumberFilters))
                .addGap(18, 18, 18)
                .addGroup(jPanelFiltersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelFiltersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButtonFilter)
                        .addComponent(jButtonCancel)
                        .addComponent(jButtonUNDO))
                    .addComponent(jButtonUPdate))
                .addContainerGap(173, Short.MAX_VALUE))
        );

        jPanelFiltersLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jRadioButtonDecvice, jRadioButtonNOTdevice, jRadioButtonNOTlocation, jRadioButtonNOTtime, jRadioButtonTime});

        jTabbedPanelTask.addTab("Filter", jPanelFilters);
        jPanelFilters.getAccessibleContext().setAccessibleName("Filters");

        jPanelSQL.setBackground(new java.awt.Color(156, 250, 58));
        jPanelSQL.setMinimumSize(new java.awt.Dimension(660, 450));
        jPanelSQL.setPreferredSize(new java.awt.Dimension(660, 450));
        jPanelSQL.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                jPanelSQLAncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
        });

        jLabelIP.setText("IP:");

        jFormattedTextFieldIP.setColumns(18);
        try {
            jFormattedTextFieldIP.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###.###")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jFormattedTextFieldIP.setText("005.029.193.052");
        jFormattedTextFieldIP.setToolTipText("");
        jFormattedTextFieldIP.setMaximumSize(new java.awt.Dimension(110, 25));
        jFormattedTextFieldIP.setMinimumSize(new java.awt.Dimension(110, 25));
        jFormattedTextFieldIP.setPreferredSize(new java.awt.Dimension(110, 25));

        jLabelPORT.setText("PORT:");

        jFormattedTextFieldPORT.setColumns(5);
        jFormattedTextFieldPORT.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));
        jFormattedTextFieldPORT.setText("3306");
        jFormattedTextFieldPORT.setMaximumSize(new java.awt.Dimension(60, 25));
        jFormattedTextFieldPORT.setMinimumSize(new java.awt.Dimension(60, 25));
        jFormattedTextFieldPORT.setPreferredSize(new java.awt.Dimension(60, 25));

        jLabelUSER.setText("USER:");

        jTextFieldUSER.setText("oop1");
        jTextFieldUSER.setMaximumSize(new java.awt.Dimension(260, 25));
        jTextFieldUSER.setMinimumSize(new java.awt.Dimension(260, 25));
        jTextFieldUSER.setName(""); // NOI18N
        jTextFieldUSER.setPreferredSize(new java.awt.Dimension(260, 25));

        jLabelPASSWORD.setText("PASSWORD:");

        jTextFieldPASSWORD.setText("Lambda1();");
        jTextFieldPASSWORD.setMaximumSize(new java.awt.Dimension(260, 25));
        jTextFieldPASSWORD.setMinimumSize(new java.awt.Dimension(260, 25));
        jTextFieldPASSWORD.setPreferredSize(new java.awt.Dimension(260, 25));

        jLabelDB.setText("DATABASE:");

        jTextFieldDB.setText("oop_course_ariel");
        jTextFieldDB.setMaximumSize(new java.awt.Dimension(260, 25));
        jTextFieldDB.setMinimumSize(new java.awt.Dimension(260, 25));
        jTextFieldDB.setPreferredSize(new java.awt.Dimension(260, 25));

        jLabelTABLE.setText("TABLE:");

        jTextFieldTable.setText("ex4_db");
        jTextFieldTable.setMaximumSize(new java.awt.Dimension(260, 25));
        jTextFieldTable.setMinimumSize(new java.awt.Dimension(260, 25));
        jTextFieldTable.setPreferredSize(new java.awt.Dimension(260, 25));

        jButtonConnect.setText("Connect");
        jButtonConnect.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonConnectActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelSQLLayout = new javax.swing.GroupLayout(jPanelSQL);
        jPanelSQL.setLayout(jPanelSQLLayout);
        jPanelSQLLayout.setHorizontalGroup(
            jPanelSQLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelSQLLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelSQLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelSQLLayout.createSequentialGroup()
                        .addGroup(jPanelSQLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jTextFieldDB, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabelUSER, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldUSER, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(jPanelSQLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelSQLLayout.createSequentialGroup()
                                .addGap(54, 54, 54)
                                .addGroup(jPanelSQLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanelSQLLayout.createSequentialGroup()
                                        .addComponent(jLabelTABLE)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addComponent(jTextFieldTable, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelSQLLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanelSQLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelSQLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabelPASSWORD)
                                        .addComponent(jTextFieldPASSWORD, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jButtonConnect, javax.swing.GroupLayout.Alignment.TRAILING))))
                        .addGap(71, 71, 71))
                    .addGroup(jPanelSQLLayout.createSequentialGroup()
                        .addGroup(jPanelSQLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelSQLLayout.createSequentialGroup()
                                .addGroup(jPanelSQLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabelIP)
                                    .addComponent(jFormattedTextFieldIP, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(52, 52, 52)
                                .addGroup(jPanelSQLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabelPORT)
                                    .addComponent(jFormattedTextFieldPORT, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jLabelDB))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanelSQLLayout.setVerticalGroup(
            jPanelSQLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelSQLLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanelSQLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelIP)
                    .addComponent(jLabelPORT))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelSQLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jFormattedTextFieldIP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jFormattedTextFieldPORT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelSQLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelUSER)
                    .addComponent(jLabelPASSWORD))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelSQLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldUSER, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldPASSWORD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelSQLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelDB)
                    .addComponent(jLabelTABLE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelSQLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldDB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldTable, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addComponent(jButtonConnect)
                .addContainerGap(188, Short.MAX_VALUE))
        );

        jTabbedPanelTask.addTab("SQL", jPanelSQL);

        getContentPane().add(jTabbedPanelTask, java.awt.BorderLayout.PAGE_START);
        jTabbedPanelTask.getAccessibleContext().setAccessibleName("TabbedPanels");

        fileMenu.setMnemonic('F');
        fileMenu.setText("File");

        aboutMenuItem.setMnemonic('A');
        aboutMenuItem.setText("About");
        aboutMenuItem.setToolTipText("About");
        aboutMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aboutMenuItemActionPerformed(evt);
            }
        });
        fileMenu.add(aboutMenuItem);

        exitMenuItem.setMnemonic('E');
        exitMenuItem.setText("Exit");
        exitMenuItem.setToolTipText("Quit Team, Quit!");
        exitMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitMenuItemActionPerformed(evt);
            }
        });
        fileMenu.add(exitMenuItem);

        mainMenu.add(fileMenu);

        setJMenuBar(mainMenu);
        mainMenu.getAccessibleContext().setAccessibleName("");

        getAccessibleContext().setAccessibleDescription("");
    }// </editor-fold>//GEN-END:initComponents
    //user choose 'About'
    private void aboutMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aboutMenuItemActionPerformed
        new About(this).setVisible(true);
    }//GEN-LAST:event_aboutMenuItemActionPerformed
    //user chooce exit from application
    private void exitMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitMenuItemActionPerformed
        System.exit(0);
    }//GEN-LAST:event_exitMenuItemActionPerformed
    //user choose 'X'
    private void exitForm(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_exitForm
        System.exit(0);
    }//GEN-LAST:event_exitForm
  //this function writes database in kml format
    private void jButtonSaveKMLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSaveKMLActionPerformed
        String str=hf.SaveKML();
        jTextFieldSaveKml.setText(str);
    }//GEN-LAST:event_jButtonSaveKMLActionPerformed
    //the functon show data about number of WiFi and rows in database
    private void jButtonShowDataActionPerformed(java.awt.event.ActionEvent evt){//GEN-FIRST:event_jButtonShowDataActionPerformed
    	jTextFieldShowData.setText(hf.ShowData());
        jTextFieldFilter.setText(hf.ShowFilter());
    }//GEN-LAST:event_jButtonShowDataActionPerformed
    //the function cleaning database
    private void jButtonClearOKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonClearOKActionPerformed
        hf.Clear();
        hf.WriteFilter();
        InitializationIOPanel();
    }//GEN-LAST:event_jButtonClearOKActionPerformed
    //the function browse a folder with the Wigle files
    private void jButtonBrowseFolderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBrowseFolderActionPerformed
        jTextFieldNameFolder.setText(hf.BrowseFolder());
    }//GEN-LAST:event_jButtonBrowseFolderActionPerformed
    //the function browse the Wigle file
    private void jButtonBrowseFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBrowseFileActionPerformed
        jTextFieldNameFile.setText(hf.BrowseFile());
    }//GEN-LAST:event_jButtonBrowseFileActionPerformed
    //the function save special file
    private void jButtonSaveFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSaveFileActionPerformed
        jTextFieldNameSaveFile.setText(hf.SaveFile());
    }//GEN-LAST:event_jButtonSaveFileActionPerformed
    //the function add data from wigle file to database
    private void jButtonOKFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonOKFileActionPerformed
        File file = new File(jTextFieldNameFile.getText());
        SimpleDateFormat sdf = new SimpleDateFormat("MM/dd/yyyy HH:mm:ss");
        hf.AddFile(jTextFieldNameFile.getText());
        TableFiles.putIfAbsent(jTextFieldNameFile.getText(),sdf.format(file.lastModified()));
        hf.WriteFilter();
        jTextFieldNameFile.setText("Name File");
    }//GEN-LAST:event_jButtonOKFileActionPerformed
    //the function add data from wigle folder to database
    private void jButtonOKFolderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonOKFolderActionPerformed
        File file = new File(jTextFieldNameFolder.getText());
        SimpleDateFormat sdf = new SimpleDateFormat("MM/dd/yyyy HH:mm:ss");
        hf.AddFolder(jTextFieldNameFolder.getText());
        TableFolder.putIfAbsent(jTextFieldNameFolder.getText(),sdf.format(file.lastModified()));
        hf.WriteFilter();
        jTextFieldNameFolder.setText("Name Folder");
    }//GEN-LAST:event_jButtonOKFolderActionPerformed
    //the function makes the first algorithm
    private void jButtonFirstALGOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonFirstALGOActionPerformed
        Location lla=hf.FirstAlgorithm(jFormattedTextFieldMACfa.getText());
        jTextFieldLantitude.setText(String.valueOf(lla.getLat()));
        jTextFieldLongtitude.setText(String.valueOf(lla.getLon()));
        jTextFieldAltitude.setText(String.valueOf(lla.getAlt()));
    }//GEN-LAST:event_jButtonFirstALGOActionPerformed
    //the function makes the second algorithms for 3 mac
    private void jButtonOKThreeMACActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonOKThreeMACActionPerformed
        try{
        //variables
        ArrayList<DataWIFI> dwf;
        DataWIFI ThreeMAC=new DataWIFI();
        Location place;
        WIFI tmp1=new WIFI();   WIFI tmp2=new WIFI();   WIFI tmp3=new WIFI();
        if (tmp1.setMAC(jFormattedTextFieldMAC1.getText().toLowerCase())==1)
        {
            if (tmp1.setSignal(Integer.parseInt(jFormattedTextFieldSignal1.getText()))==1)
                ThreeMAC.setWiFi(tmp1);
        }
        if (tmp2.setMAC(jFormattedTextFieldMAC2.getText().toLowerCase())==1)
        {
            if (tmp2.setSignal(Integer.parseInt(jFormattedTextFieldSignal2.getText()))==1)
                ThreeMAC.setWiFi(tmp2);
        }
        if (tmp3.setMAC(jFormattedTextFieldMAC3.getText().toLowerCase())==1)
        {
            if (tmp3.setSignal(Integer.parseInt(jFormattedTextFieldSignal3.getText()))==1)
                ThreeMAC.setWiFi(tmp3);
        }
        dwf=ReadFunctions.ReadDataBase();
        place=hf.ThreeMac(dwf,ThreeMAC);
        jTextFieldLantitude.setText(String.valueOf(place.getLat()));
        jTextFieldLongtitude.setText(String.valueOf(place.getLon()));
        jTextFieldAltitude.setText(String.valueOf(place.getAlt()));
        }catch(NumberFormatException e){
            JOptionPane.showMessageDialog(null, "Input is incorrect");
        }
    }//GEN-LAST:event_jButtonOKThreeMACActionPerformed
    //the function uses the second algotithm for row as comb_no_gps_ts1.csv
    private void jButtonOKGPSTSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonOKGPSTSActionPerformed
        //variables
        String str=jTextFieldRowTS.getText();
        ArrayList<DataWIFI> dwf;
        Location place;
        dwf=ReadFunctions.ReadDataBase();
        place=hf.RowTS(dwf,str);
        jTextFieldLantitude.setText(String.valueOf(place.getLat()));
        jTextFieldLongtitude.setText(String.valueOf(place.getLon()));
        jTextFieldAltitude.setText(String.valueOf(place.getAlt()));
    }//GEN-LAST:event_jButtonOKGPSTSActionPerformed
    //the function create filter
    private void jButtonFilterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonFilterActionPerformed
        try{
            Filter tmp = null;
            if (jRadioButtonTime.isSelected() || jRadioButtonNOTtime.isSelected())
            {
                if (jRadioButtonNOTtime.isSelected())
                    tmp=new NOT(new TimeFilter(jFormattedTextFieldFROM.getText(),jFormattedTextFieldTO.getText()));
                else
                    tmp=new TimeFilter(jFormattedTextFieldFROM.getText(),jFormattedTextFieldTO.getText());
            }
            else
                if (jRadioButtonLocation.isSelected() || jRadioButtonNOTlocation.isSelected())
                {
                    Location lla=new Location();
                    double rad=Double.parseDouble(jFormattedTextFieldRadius.getText().replace(',', '.'));
                    lla.setLat(Double.parseDouble(jFormattedTextFieldLantitude.getText().replace(',', '.')));
                    lla.setLon(Double.parseDouble(jFormattedTextFieldLantitude.getText().replace(',', '.')));
                    if (jRadioButtonNOTlocation.isSelected())
                        tmp=new NOT(new LocationFilter(rad,lla));
                    else
                        tmp=new LocationFilter(rad,lla);
                }
                else
                    if(jRadioButtonDecvice.isSelected() || jRadioButtonNOTdevice.isSelected())
                    {
                        if(jRadioButtonNOTdevice.isSelected())
                            tmp=new NOT(new DeviceFilter(jTextFieldDeviceName.getText()));
                        else
                            tmp=new DeviceFilter(jTextFieldDeviceName.getText());
                    }
            switch (flag) {
                case 0:
                    first=tmp;
                    flag++;
                    jLabelNumberFilters.setText("1");
                    break;
                case 1:
                    second=tmp;
                    flag++;
                    if(jRadioButtonOr.isSelected())
                        union=new OR(first,second);
                    else
                        union=new AND(first,second);
                    jLabelNumberFilters.setText("2");
                    break;
                default:
                    JOptionPane.showMessageDialog(null, "max two filters");
                    break;
            }
        }catch(NullPointerException | NumberFormatException e){
            JOptionPane.showMessageDialog(null, "Input is incorrect");
        }
    }//GEN-LAST:event_jButtonFilterActionPerformed
    //the function back 
    private void jButtonCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelActionPerformed
        if (flag==2)
        {
            second=null;
            union=null;
            flag--;
            jLabelNumberFilters.setText("1");
        }
        else
            if (flag==1)
                InitializationFilterPanel();
            else
                JOptionPane.showMessageDialog(null, "no filters");
    }//GEN-LAST:event_jButtonCancelActionPerformed
    //the function initialization Filter panel
    private void InitializationFilterPanel()
    {
        Date date = new Date();
        SimpleDateFormat formatter = new SimpleDateFormat("yyyy-MM-dd HH:mm:ss");
        String dateString = formatter.format(date);
        flag=0;
        union=first=second=null;
        jFormattedTextFieldRadius.setText("0,03");
        jTextFieldDeviceName.setText("Device name");
        jFormattedTextFieldLantitude.setText("32,103");
        jFormattedTextFieldLongtitude.setText("35,203");
        jFormattedTextFieldFROM.setText(dateString);
        jFormattedTextFieldTO.setText(dateString);
        jLabelNumberFilters.setText("0");
    }
    //the function initialization IO panel
    private void InitializationIOPanel()
    {
        jTextFieldNameFolder.setText("Name Folder");
        jTextFieldNameFile.setText("Name File");
        jTextFieldNameSaveFile.setText("Save File");
        jTextFieldSaveKml.setText("KML File");
        jTextFieldShowData.setText("Data:");
        jTextFieldFilter.setText("Filter:");
    }
    //filter panel is selected and initialization of filters
    private void jPanelFiltersAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_jPanelFiltersAncestorAdded
        InitializationFilterPanel();
    }//GEN-LAST:event_jPanelFiltersAncestorAdded
   //the function update database
    private void jButtonUPdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonUPdateActionPerformed
        if (flag==1)
        {
            hf.WriteUNDO();
            hf.WriteFilter(first);
            InitializationFilterPanel();
            flag_UNDO=true;
        }
        else
            if (flag==2)
            {
                hf.WriteUNDO();
                hf.WriteFilter(union);
                InitializationFilterPanel();
                flag_UNDO=true;
            }
            else
                JOptionPane.showMessageDialog(null, "no filters");
    }//GEN-LAST:event_jButtonUPdateActionPerformed
    //IO panel is selected and initialization of text
    private void jPanelIOputAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_jPanelIOputAncestorAdded
        InitializationIOPanel();
    }//GEN-LAST:event_jPanelIOputAncestorAdded
    //Algo panel is selected and initialization of text
    private void jPanelALGOAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_jPanelALGOAncestorAdded
        jTextFieldRowTS.setText("row as comb_no_gps_ts1.csv");
        jFormattedTextFieldMACfa.setText("AA:BB:CC:11:22:33");
        jFormattedTextFieldMAC1.setText("11:22:33:AA:BB:CC");
        jFormattedTextFieldMAC2.setText("11:22:33:AA:BB:CC");
        jFormattedTextFieldMAC3.setText("11:22:33:AA:BB:CC");
        jFormattedTextFieldSignal1.setText("");
        jFormattedTextFieldSignal2.setText("");
        jFormattedTextFieldSignal3.setText("");
        jTextFieldLantitude.setText("");
        jTextFieldLongtitude.setText("");
        jTextFieldAltitude.setText("");
    }//GEN-LAST:event_jPanelALGOAncestorAdded
    //user choose UNDO
    private void jButtonUNDOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonUNDOActionPerformed
        if (flag_UNDO)
        {
            hf.UNDO();
            flag_UNDO=false;
        }
        else
            JOptionPane.showMessageDialog(null, "once can be done");
    }//GEN-LAST:event_jButtonUNDOActionPerformed
    //the function initialization SQL panel
    private void InitializationSQLPanel()
    {
        jFormattedTextFieldIP.setText("005.029.193.052");
        jFormattedTextFieldPORT.setText("3306");
        jTextFieldUSER.setText("oop1");
        jTextFieldPASSWORD.setText("Lambda1();");
        jTextFieldDB.setText("oop_course_ariel");
        jTextFieldTable.setText("ex4_db");
    }
    //SQL panel is selected and initialization of text
    private void jPanelSQLAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_jPanelSQLAncestorAdded
        InitializationSQLPanel();
    }//GEN-LAST:event_jPanelSQLAncestorAdded
    //user select connect to SQL database
    private void jButtonConnectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonConnectActionPerformed
        String all=jFormattedTextFieldIP.getText()+","+jFormattedTextFieldPORT.getText()+","+jTextFieldUSER.getText()+
                   ","+jTextFieldPASSWORD.getText()+","+jTextFieldDB.getText()+","+jTextFieldTable.getText();
        String[] args=all.split(",");
        ArrayList<DataWIFI> dwf=readSQL.Connect(args);
        hf.AddSQL(dwf);
        TableSQL.putIfAbsent(all,hf.TimeUpdate(args));
    }//GEN-LAST:event_jButtonConnectActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem aboutMenuItem;
    private javax.swing.ButtonGroup buttonGroupLogical;
    private javax.swing.ButtonGroup buttonGroupTypeFilter;
    private javax.swing.JMenuItem exitMenuItem;
    private javax.swing.JMenu fileMenu;
    private javax.swing.JButton jButtonBrowseFile;
    private javax.swing.JButton jButtonBrowseFolder;
    private javax.swing.JButton jButtonCancel;
    private javax.swing.JButton jButtonClearOK;
    private javax.swing.JButton jButtonConnect;
    private javax.swing.JButton jButtonFilter;
    private javax.swing.JButton jButtonFirstALGO;
    private javax.swing.JButton jButtonOKFile;
    private javax.swing.JButton jButtonOKFolder;
    private javax.swing.JButton jButtonOKGPSTS;
    private javax.swing.JButton jButtonOKThreeMAC;
    private javax.swing.JButton jButtonSaveFile;
    private javax.swing.JButton jButtonSaveKML;
    private javax.swing.JButton jButtonShowData;
    private javax.swing.JButton jButtonUNDO;
    private javax.swing.JButton jButtonUPdate;
    private javax.swing.JFormattedTextField jFormattedTextFieldFROM;
    private javax.swing.JFormattedTextField jFormattedTextFieldIP;
    private javax.swing.JFormattedTextField jFormattedTextFieldLantitude;
    private javax.swing.JFormattedTextField jFormattedTextFieldLongtitude;
    private javax.swing.JFormattedTextField jFormattedTextFieldMAC1;
    private javax.swing.JFormattedTextField jFormattedTextFieldMAC2;
    private javax.swing.JFormattedTextField jFormattedTextFieldMAC3;
    private javax.swing.JFormattedTextField jFormattedTextFieldMACfa;
    private javax.swing.JFormattedTextField jFormattedTextFieldPORT;
    private javax.swing.JFormattedTextField jFormattedTextFieldRadius;
    private javax.swing.JFormattedTextField jFormattedTextFieldSignal1;
    private javax.swing.JFormattedTextField jFormattedTextFieldSignal2;
    private javax.swing.JFormattedTextField jFormattedTextFieldSignal3;
    private javax.swing.JFormattedTextField jFormattedTextFieldTO;
    private javax.swing.JLabel jLabelAND;
    private javax.swing.JLabel jLabelAddFile;
    private javax.swing.JLabel jLabelAddFolder;
    private javax.swing.JLabel jLabelAltitude;
    private javax.swing.JLabel jLabelCB;
    private javax.swing.JLabel jLabelDB;
    private javax.swing.JLabel jLabelDevice;
    private javax.swing.JLabel jLabelFROMTime;
    private javax.swing.JLabel jLabelFirstAlgorithm;
    private javax.swing.JLabel jLabelIP;
    private javax.swing.JLabel jLabelLantitude;
    private javax.swing.JLabel jLabelLocation;
    private javax.swing.JLabel jLabelLongtitude;
    private javax.swing.JLabel jLabelMAC1;
    private javax.swing.JLabel jLabelMAC2;
    private javax.swing.JLabel jLabelMAC3;
    private javax.swing.JLabel jLabelMACfa;
    private javax.swing.JLabel jLabelNOT;
    private javax.swing.JLabel jLabelNumberFilters;
    private javax.swing.JLabel jLabelOR;
    private javax.swing.JLabel jLabelPASSWORD;
    private javax.swing.JLabel jLabelPORT;
    private javax.swing.JLabel jLabelRadius;
    private javax.swing.JLabel jLabelRow;
    private javax.swing.JLabel jLabelSD;
    private javax.swing.JLabel jLabelSK;
    private javax.swing.JLabel jLabelSalgorithm;
    private javax.swing.JLabel jLabelShowData;
    private javax.swing.JLabel jLabelSignal1;
    private javax.swing.JLabel jLabelSignal2;
    private javax.swing.JLabel jLabelSignal3;
    private javax.swing.JLabel jLabelTABLE;
    private javax.swing.JLabel jLabelTOTime;
    private javax.swing.JLabel jLabelTime;
    private javax.swing.JLabel jLabelUSER;
    private javax.swing.JLabel jLabelX;
    private javax.swing.JLabel jLabelY;
    private javax.swing.JPanel jPanelALGO;
    private javax.swing.JPanel jPanelFilters;
    private javax.swing.JPanel jPanelIOput;
    private javax.swing.JPanel jPanelSQL;
    private javax.swing.JRadioButton jRadioButtonAnd;
    private javax.swing.JRadioButton jRadioButtonDecvice;
    private javax.swing.JRadioButton jRadioButtonLocation;
    private javax.swing.JRadioButton jRadioButtonNOTdevice;
    private javax.swing.JRadioButton jRadioButtonNOTlocation;
    private javax.swing.JRadioButton jRadioButtonNOTtime;
    private javax.swing.JRadioButton jRadioButtonOr;
    private javax.swing.JRadioButton jRadioButtonTime;
    private javax.swing.JTabbedPane jTabbedPanelTask;
    private javax.swing.JTextField jTextFieldAltitude;
    private javax.swing.JTextField jTextFieldDB;
    private javax.swing.JTextField jTextFieldDeviceName;
    private javax.swing.JTextField jTextFieldFilter;
    private javax.swing.JTextField jTextFieldLantitude;
    private javax.swing.JTextField jTextFieldLongtitude;
    private javax.swing.JTextField jTextFieldNameFile;
    private javax.swing.JTextField jTextFieldNameFolder;
    private javax.swing.JTextField jTextFieldNameSaveFile;
    private javax.swing.JTextField jTextFieldPASSWORD;
    private javax.swing.JTextField jTextFieldRowTS;
    private javax.swing.JTextField jTextFieldSaveKml;
    private javax.swing.JTextField jTextFieldShowData;
    private javax.swing.JTextField jTextFieldTable;
    private javax.swing.JTextField jTextFieldUSER;
    private javax.swing.JMenuBar mainMenu;
    // End of variables declaration//GEN-END:variables
    //the function set icon to JFrame
//    private void setIcon()
//    {
//        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("WiFi.jpg")));
//    }
    //run GUI
    private static class RunnableImpl implements Runnable {

        public RunnableImpl() {
        }
        @Override
        public void run()
        {
            new AppAS().setVisible(true);
        }
    }
    //run TableFiles
    private static class ThreadTable extends Thread {
        public ThreadTable() {
        }
        //run for thread update
        public void run() {
            SimpleDateFormat sdf = new SimpleDateFormat("MM/dd/yyyy HH:mm:ss");
            while(true)
            {
                for (Map.Entry<String, String> pair: TableFiles.entrySet())
                {
                    File file = new File(pair.getKey());
                    //file deleted
                    if (!file.exists())
                        TableFiles.remove(pair.getKey(), pair.getValue());
                    else                                    //file is modificate
                        if (!sdf.format(file.lastModified()).equals(pair.getValue()))
                        {
                            hf.AddFile(pair.getKey());
                            TableFiles.replace(pair.getKey(),sdf.format(file.lastModified()));
                        }
                }
            }
        }
    }
    //run TableFolder
    private static class ThreadTableFolder extends Thread 
    {
        public ThreadTableFolder() {
        }
        //run for thread update
        @Override
        public void run()
        {
            SimpleDateFormat sdf = new SimpleDateFormat("MM/dd/yyyy HH:mm:ss");
            while(true)
            {
                for (Map.Entry<String, String> pair: TableFolder.entrySet())
                {
                    File file = new File(pair.getKey());
                    //file deleted
                    if (!file.exists())
                        TableFolder.remove(pair.getKey(), pair.getValue());
                    else                                    //folder is modificate
                        if (!sdf.format(file.lastModified()).equals(pair.getValue()))
                        {
                            hf.AddFolder(pair.getKey());
                            TableFolder.replace(pair.getKey(),sdf.format(file.lastModified()));
                        }
                }
            }
        }
    }
    //run TableSQL
    private static class ThreadTableSQL extends Thread 
    {
        public ThreadTableSQL() {
        }
        //run for thread update
        @Override
        public void run()
        {
            while(true)
            {
                TableSQL.entrySet().forEach((pair) -> 
                {
                    try {
                	String[] args = pair.getKey().split(",");
                    //sql table is modificate
                    if (!hf.TimeUpdate(args).equals(pair.getValue())) {
                        ArrayList<DataWIFI> dwf=readSQL.Connect(args);
                        hf.AddSQL(dwf);
                        TableSQL.replace(pair.getKey(),hf.TimeUpdate(args));
                    }}catch(NullPointerException e){
                    	TableSQL.remove(pair.getKey());
                    }
                });
                try {
                    Thread.sleep(1000);
                }catch(InterruptedException ex) {
                    System.out.println("No sleep Ex3.AppAS.ThreadTableSQL.run()");
                }
            }
        }
    }
}